In [97]:
import pandas as pd
import numpy as np

# url_2019_to_2020 = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/10302020-annual-report-on-student-discipline--students--multiple--removals--suspensions-r.xlsx'
# url_2018_to_2019 = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/10102019-annual-report-on-student-recidivists-mf-redacted-for-review.xlsx'
# url_2017_to_2018 = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/students-with-multiple-removals-or-suspensions-2018-english.xlsx'
# url_2016_to_2017 = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/11022017annualreportonstudentrecidivistsredactedmfforreview.xlsx'
# url_2015_to_2016 = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/10132016annualreportonstudentrecidivists.xlsx'

url_2019_to_2020_student_discipline = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/original_data_sets/blue_team/2020-2019/10302020-annual-report-on-student-discipline-final-redacted.xlsx'
url_2019_to_2020_nypd_contact = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/original_data_sets/blue_team/2020-2019/1030020-annual-report-on-nypd-contacts--student-discipline-final-redacted.xlsx'

url_2018_to_2019_student_discipline = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/original_data_sets/blue_team/2019-2018/10082019-annual-report-on-student-discipline-mf-redacted-for-review.xlsx'
url_2018_to_2019_nypd_contact = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/original_data_sets/blue_team/2019-2018/10112019-annual-report-on-nypd-contacts--student-discipline-mf-redacted-for-review.xlsx'

url_2017_to_2018_student_discipline = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/original_data_sets/blue_team/2018-2017/10262018-annual-report-on-student-discipline-redacted-final-shared.xlsx'
url_2017_to_2018_nypd_contact = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/original_data_sets/blue_team/2018-2017/nypd-contacts-that-resulted-in-suspension-2018-english.xlsx'

url_2016_to_2017_student_discipline = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/original_data_sets/blue_team/2017-2016/11022017annualreportonstudentdisciplinemfredactedforreview.xlsx'
url_2016_to_2017_nypd_contact = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/original_data_sets/blue_team/2017-2016/11022017annualreportonnypdcontactsstudentdisciplineredactedmfforreview.xlsx'

url_2015_to_2016_student_discipline = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/original_data_sets/blue_team/2016-2015/10042016annualreportonstudentdiscipline.xlsx'
url_2015_to_2016_nypd_contact = 'https://raw.githubusercontent.com/desmondbera/team-81/main/data_sets/original_data_sets/blue_team/2016-2015/10132016annualreportonnypdcontactsstudentdiscipline.xlsx'

In [189]:
def drop_last_row(df):
    return df.drop(df.tail(1).index)

def lower_case_col_names(df):
    return df.rename(columns=str.lower, inplace=True)

def rename_col_from(col_name, col_name_change, df):
    return df.rename(columns={col_name: col_name_change}, inplace=True)

#NOTE: we arrive to this number because 'R' is used for values between 1-5 (inclusive) but cannot be shown for privacy concerns. 
# As a result, we take the avg of 1+2+3+4+5 => 3
def change_r_occurence(df_race, df_gender, df_discipline, year):
    if(year == 2020):
        discipline_cols_with_r_val = ['principal', 'removal', 'superintendent',
           'sy1920_total_removals_suspensions']
        race_cols_with_r_val = ['american indian/alaskan native removals and/or suspensions resulting from incidents where nypd was contacted',
           'asian removals and/or suspensions resulting from incidents where nypd was contacted',
           'black removals and/or suspensions resulting from incidents where nypd was contacted',
           'hispanic removals and/or suspensions resulting from incidents where nypd was contacted',
           'multi-racial removals and/or suspensions resulting from incidents where nypd was contacted',
           'unknown removals and/or suspensions resulting from incidents where nypd was contacted',
           'white removals and/or suspensions resulting from incidents where nypd was contacted', 'sy1920_total_removals_suspensions removals and/or suspensions resulting from incidents where nypd was contacted'] 
        gender_cols_with_r_val = ['female removals and/or suspensions resulting from incidents where nypd was contacted',
           'male removals and/or suspensions resulting from incidents where nypd was contacted', 'sy1920_total_removals_suspensions removals and/or suspensions resulting from incidents where nypd was contacted']
        df_race[race_cols_with_r_val] = df_race[race_cols_with_r_val].replace(to_replace={'R': 3})
        df_gender[gender_cols_with_r_val] = df_gender[gender_cols_with_r_val].replace(to_replace={'R': 3})
        df_discipline[discipline_cols_with_r_val] = df_discipline[discipline_cols_with_r_val].replace(to_replace={'R': 3})
    elif(year == 2019):
        discipline_cols_with_r_val = ['removal', 'principal', 'superintendent', 'sy1819 total removals/suspensions']
        race_cols_with_r_val = ['american indian/alaskan native removals or suspensions resulting from incidents where nypd was contacted',
       'asian removals or suspensions resulting from incidents where nypd was contacted',
       'black removals or suspensions resulting from incidents where nypd was contacted',
       'hispanic removals or suspensions resulting from incidents where nypd was contacted',
       'white removals or suspensions resulting from incidents where nypd was contacted',
       'multi-racial removals or suspensions resulting from incidents where nypd was contacted',
       'unknown removals or suspensions resulting from incidents where nypd was contacted',
       'total removals or suspensions resulting from incidents where nypd was contacted']
        gender_cols_with_r_val =['male removals or suspensions resulting from incidents where nypd was contacted',
       'female removals or suspensions resulting from incidents where nypd was contacted',
       'total removals or suspensions resulting from incidents where nypd was contacted']
        df_race[race_cols_with_r_val] = df_race[race_cols_with_r_val].replace(to_replace={'R': 3})
        df_gender[gender_cols_with_r_val] = df_gender[gender_cols_with_r_val].replace(to_replace={'R': 3})
        df_discipline[discipline_cols_with_r_val] = df_discipline[discipline_cols_with_r_val].replace(to_replace={'R': 3})
    elif(year == 2018):
        print("year is 2018")
        discipline_cols_with_r_val = ['removal','principal', 'superintendent','sy1718 total removals/suspensions']
        race_cols_with_r_val = ['american indian/alaskan native removals or suspensions resulting from incidents where nypd was contacted',
       'asian removals or suspensions resulting from incidents where nypd was contacted',
       'black removals or suspensions resulting from incidents where nypd was contacted',
       'hispanic removals or suspensions resulting from incidents where nypd was contacted',
       'white removals or suspensions resulting from incidents where nypd was contacted',
       'multi-racial removals or suspensions resulting from incidents where nypd was contacted',
       'unknown removals or suspensions resulting from incidents where nypd was contacted',
       'total removals or suspensions resulting from incidents where nypd was contacted']
        gender_cols_with_r_val = ['male removals or suspensions resulting from incidents where nypd was contacted',
       'female removals or suspensions resulting from incidents where nypd was contacted',
       'total removals or suspensions resulting from incidents where nypd was contacted']
        
        df_race[race_cols_with_r_val] = df_race[race_cols_with_r_val].replace(to_replace={'R': 3})
        df_gender[gender_cols_with_r_val] = df_gender[gender_cols_with_r_val].replace(to_replace={'R': 3})
        df_discipline[discipline_cols_with_r_val] = df_discipline[discipline_cols_with_r_val].replace(to_replace={'R': 3})
    elif(year == 2017):
        print("year is 2017")
        discipline_cols_with_r_val = ['removal', 'principal', 'superintendent', 'expulsions', 'sy1718 total removals/suspensions']
        race_cols_with_r_val = ['american indian/alaskan native removals or suspensions resulting from incidents where nypd was contacted',
       'asian removals or suspensions resulting from incidents where nypd was contacted',
       'black removals or suspensions resulting from incidents where nypd was contacted',
       'hispanic removals or suspensions resulting from incidents where nypd was contacted',
       'white removals or suspensions resulting from incidents where nypd was contacted',
       'multi-racial removals or suspensions resulting from incidents where nypd was contacted',
       'unknown removals or suspensions resulting from incidents where nypd was contacted',
       'total removals or suspensions resulting from incidents where nypd was contacted']
        gender_cols_with_r_val = ['male removals or suspensions resulting from incidents where nypd was contacted',
       'female removals or suspensions resulting from incidents where nypd was contacted',
       'total removals or suspensions resulting from incidents where nypd was contacted']
        
        df_race[race_cols_with_r_val] = df_race[race_cols_with_r_val].replace(to_replace={'R': 3})
        df_gender[gender_cols_with_r_val] = df_gender[gender_cols_with_r_val].replace(to_replace={'R': 3})
        df_discipline[discipline_cols_with_r_val] = df_discipline[discipline_cols_with_r_val].replace(to_replace={'R': 3})
    elif(year == 2016):
        print("year is 2016")
        discipline_cols_with_r_val = ['removal', 'principal', 'superintendent', 'expulsions', 'sy1718 total removals/suspensions']
        race_cols_with_r_val = ['american indian/alaskan native removals or suspensions resulting from incidents where nypd was contacted',
       'asian removals or suspensions resulting from incidents where nypd was contacted',
       'black removals or suspensions resulting from incidents where nypd was contacted',
       'hispanic removals or suspensions resulting from incidents where nypd was contacted',
       'white removals or suspensions resulting from incidents where nypd was contacted',
       'multi-racial removals or suspensions resulting from incidents where nypd was contacted',
       'unknown removals or suspensions resulting from incidents where nypd was contacted',
       'total removals or suspensions resulting from incidents where nypd was contacted']
        gender_cols_with_r_val = ['male removals or suspensions resulting from incidents where nypd was contacted',
       'female removals or suspensions resulting from incidents where nypd was contacted',
       'total removals or suspensions resulting from incidents where nypd was contacted']
        
        df_race[race_cols_with_r_val] = df_race[race_cols_with_r_val].replace(to_replace={'R': 3})
        df_gender[gender_cols_with_r_val] = df_gender[gender_cols_with_r_val].replace(to_replace={'R': 3})
        df_discipline[discipline_cols_with_r_val] = df_discipline[discipline_cols_with_r_val].replace(to_replace={'R': 3})
    else:
        print("This year does not exists in our change_r_occcurence function")
    return df_race, df_gender, df_discipline

def save_df_to_csv(df, file_name, year):
    df.to_csv(file_name+'_' + year +'.csv', encoding='utf-8')

In [91]:
### 1. Datasets from 2020-2019 
#    -- 3 sheets in total
#    -- Result: 1 dataframe that has all of our relevant colum

xls_2020_discipline = pd.ExcelFile(url_2019_to_2020_student_discipline)
xls_2020_nypd_contacts = pd.ExcelFile(url_2019_to_2020_nypd_contact)

df_discipline_totals = pd.read_excel(xls_2020_discipline, index_col=0, sheet_name='Annual Report--R-P-S TOTALS', engine='openpyxl')
df_nypd_contact_race = pd.read_excel(xls_2020_nypd_contacts, index_col=0, sheet_name='NYPD-SUSP--RACE', engine='openpyxl')
df_nypd_contact_gender = pd.read_excel(xls_2020_nypd_contacts, index_col=0, sheet_name='NYPD-SUSP--GENDER', engine='openpyxl')

## 1 - DROP LAST ROW WITH NAN + TOTAL INFO
final_df_discipline_totals = drop_last_row(df_discipline_totals)
final_df_nypd_contact_race = drop_last_row(df_nypd_contact_race)
final_df_nypd_contact_gender = drop_last_row(df_nypd_contact_gender)

## 2 - LOWER CASE COL NAMES & REPLACE EMPTY SPACES WITH UNDERSCORES
# list(final_df_discipline_totals.columns)
lower_case_col_names(final_df_discipline_totals)
lower_case_col_names(final_df_nypd_contact_race)
lower_case_col_names(final_df_nypd_contact_gender)

## 3 - CHANGE COL NAMES TO BE MORE DESCRIPTIVE
rename_col_from('location_name', 'school_name', final_df_discipline_totals)
rename_col_from('location_category_description', 'school_type', final_df_discipline_totals)

rename_col_from('location_name', 'school_name', final_df_nypd_contact_race)
rename_col_from('location_category_description', 'school_type', final_df_nypd_contact_race)

rename_col_from('location_name', 'school_name', final_df_nypd_contact_gender)
rename_col_from('location_category_description', 'school_type', final_df_nypd_contact_gender)

## 4 - CHANGE 'R' occurences to int 3
df_tuple = change_r_occurence(final_df_nypd_contact_race, final_df_nypd_contact_gender, final_df_discipline_totals, 2020)
final_df_discipline_totals = df_tuple[2]
final_df_nypd_contact_race = df_tuple[0]
final_df_nypd_contact_gender = df_tuple[1]

## 5 - CHANGE index to unique nums
final_df_discipline_totals.reset_index(inplace=True)
final_df_nypd_contact_race.reset_index(inplace=True)
final_df_nypd_contact_gender.reset_index(inplace=True)

## 6 - MERGE 4 COLS FROM STUDENT_DISCIPLINE DF to NYPD_CONTACTS_RACE
final_df_nypd_contact_race.insert(11, 'principal', final_df_discipline_totals['principal'], True)
final_df_nypd_contact_race.insert(12, 'removal', final_df_discipline_totals['removal'], True)
final_df_nypd_contact_race.insert(13, 'superintendent', final_df_discipline_totals['superintendent'], True)
final_df_nypd_contact_race.insert(14, 'expulsions', final_df_discipline_totals['expulsions'], True)

## 7 - MERGE 2 NYPD_CONTACTS_GENDER COLS to NYPD_CONTACTS_RACE
final_df_nypd_contact_race.insert(15, 'female removals and/or suspensions resulting from incidents where nypd was contacted', final_df_nypd_contact_gender['female removals and/or suspensions resulting from incidents where nypd was contacted'], True)
final_df_nypd_contact_race.insert(16, 'male removals and/or suspensions resulting from incidents where nypd was contacted', final_df_nypd_contact_gender['male removals and/or suspensions resulting from incidents where nypd was contacted'], True)

save_df_to_csv(final_df_nypd_contact_race, 'clean_df', '2020-2019')


# print(final_df_discipline_totals.dtypes)
# print("====")
# print(final_df_nypd_contact_race.head())
# print("====")
# print(final_df_nypd_contact_gender.columns)

In [129]:
### 2. Datasets from 2019-2018 
#    -- 3 sheets in total
#    -- Result: 1 dataframe that has all of our relevant columns

xls_2019_discipline = pd.ExcelFile(url_2018_to_2019_student_discipline)
xls_2019_nypd_contacts = pd.ExcelFile(url_2018_to_2019_nypd_contact)

df_discipline_totals = pd.read_excel(xls_2019_discipline, index_col=0, sheet_name='Annual Report-- R-P-S TOTALS', engine='openpyxl')
df_nypd_contact_race = pd.read_excel(xls_2019_nypd_contacts, index_col=0, sheet_name='NYPD-SUSP--RACE', engine='openpyxl')
df_nypd_contact_gender = pd.read_excel(xls_2019_nypd_contacts, index_col=0, sheet_name='NYPD-SUSP--GENDER', engine='openpyxl')

## 1 - DROP LAST ROW WITH NAN + TOTAL INFO
final_df_discipline_totals = drop_last_row(df_discipline_totals)
final_df_nypd_contact_race = drop_last_row(df_nypd_contact_race)
final_df_nypd_contact_gender = drop_last_row(df_nypd_contact_gender)

## 2 - LOWER CASE COL NAMES
lower_case_col_names(final_df_discipline_totals)
lower_case_col_names(final_df_nypd_contact_race)
lower_case_col_names(final_df_nypd_contact_gender)

## 3 - CHANGE COL NAMES TO BE MORE DESCRIPTIVE
rename_col_from('location name', 'school_name', final_df_discipline_totals)
rename_col_from('location category', 'school_type', final_df_discipline_totals)
rename_col_from('removals', 'removal', final_df_discipline_totals)

rename_col_from('location name', 'school_name', final_df_nypd_contact_race)
rename_col_from('location category', 'school_type', final_df_nypd_contact_race)

rename_col_from('location name', 'school_name', final_df_nypd_contact_gender)
rename_col_from('location category', 'school_type', final_df_nypd_contact_gender)

## 4 - CHANGE 'R' occurences to int 3
df_tuple = (
    change_r_occurence(
        final_df_nypd_contact_race, 
        final_df_nypd_contact_gender, 
        final_df_discipline_totals, 
        2019)
)
final_df_discipline_totals = df_tuple[2]
final_df_nypd_contact_race = df_tuple[0]
final_df_nypd_contact_gender = df_tuple[1]

## 5 - CHANGE index to unique nums
final_df_discipline_totals.reset_index(inplace=True)
final_df_nypd_contact_race.reset_index(inplace=True)
final_df_nypd_contact_gender.reset_index(inplace=True)

## 6 - MERGE 4 COLS FROM STUDENT_DISCIPLINE DF to NYPD_CONTACTS_RACE
final_df_nypd_contact_race.insert(11, 'principal', final_df_discipline_totals['principal'], True)
final_df_nypd_contact_race.insert(12, 'removal', final_df_discipline_totals['removal'], True)
final_df_nypd_contact_race.insert(13, 'superintendent', final_df_discipline_totals['superintendent'], True)
final_df_nypd_contact_race.insert(14, 'expulsions', final_df_discipline_totals['expulsions'], True)

## 7 - MERGE 2 NYPD_CONTACTS_GENDER COLS to NYPD_CONTACTS_RACE
final_df_nypd_contact_race.insert(15, 'female removals or suspensions resulting from incidents where nypd was contacted', final_df_nypd_contact_gender['female removals or suspensions resulting from incidents where nypd was contacted'], True)
final_df_nypd_contact_race.insert(16, 'male removals or suspensions resulting from incidents where nypd was contacted', final_df_nypd_contact_gender['male removals or suspensions resulting from incidents where nypd was contacted'], True)

save_df_to_csv(final_df_nypd_contact_race, 'clean_df', '2019-2018')

# ### --------------
# print(final_df_discipline_totals.columns)
# print("====")
# print(final_df_nypd_contact_race.head(10))
# print("====")
# print(final_df_nypd_contact_gender.columns)

# print(xls_2019_discipline.sheet_names)
# print(xls_2019_nypd_contacts.sheet_names)

year is 2019

In [169]:
### 3. Datasets from 2018-2017
#    -- 3 sheets in total
#    -- Result: 1 dataframe that has all of our relevant columns

xls_2018_discipline = pd.ExcelFile(url_2017_to_2018_student_discipline)
xls_2018_nypd_contacts = pd.ExcelFile(url_2017_to_2018_nypd_contact)

df_discipline_totals = pd.read_excel(xls_2018_discipline, index_col=0, sheet_name='Annual Report-- R-P-S TOTALS', engine='openpyxl')
df_nypd_contact_race = pd.read_excel(xls_2018_nypd_contacts, index_col=0, sheet_name='NYPD-SUSP--RACE', engine='openpyxl')
df_nypd_contact_gender = pd.read_excel(xls_2018_nypd_contacts, index_col=0, sheet_name='NYPD-SUSP--GENDER', engine='openpyxl')

## 1 - DROP LAST ROW WITH NAN + TOTAL INFO
final_df_discipline_totals = drop_last_row(df_discipline_totals)
final_df_nypd_contact_race = drop_last_row(df_nypd_contact_race)
final_df_nypd_contact_gender = drop_last_row(df_nypd_contact_gender)

## 2 - LOWER CASE COL NAMES
lower_case_col_names(final_df_discipline_totals)
lower_case_col_names(final_df_nypd_contact_race)
lower_case_col_names(final_df_nypd_contact_gender)

## 3 - CHANGE COL NAMES TO BE MORE DESCRIPTIVE
rename_col_from('location name', 'school_name', final_df_discipline_totals)
rename_col_from('location category', 'school_type', final_df_discipline_totals)
rename_col_from('removals', 'removal', final_df_discipline_totals)

rename_col_from('location name', 'school_name', final_df_nypd_contact_race)
rename_col_from('location category', 'school_type', final_df_nypd_contact_race)

rename_col_from('location name', 'school_name', final_df_nypd_contact_gender)
rename_col_from('location category', 'school_type', final_df_nypd_contact_gender)

## 4 - CHANGE 'R' occurences to int 3
df_tuple = (
    change_r_occurence(
        final_df_nypd_contact_race, 
        final_df_nypd_contact_gender, 
        final_df_discipline_totals, 
        2018)
)
final_df_discipline_totals = df_tuple[2]
final_df_nypd_contact_race = df_tuple[0]
final_df_nypd_contact_gender = df_tuple[1]

## 5 - CHANGE index to unique nums
final_df_discipline_totals.reset_index(inplace=True)
final_df_nypd_contact_race.reset_index(inplace=True)
final_df_nypd_contact_gender.reset_index(inplace=True)

## 6 - MERGE 4 COLS FROM STUDENT_DISCIPLINE DF to NYPD_CONTACTS_RACE
final_df_nypd_contact_race.insert(11, 'principal', final_df_discipline_totals['principal'], True)
final_df_nypd_contact_race.insert(12, 'removal', final_df_discipline_totals['removal'], True)
final_df_nypd_contact_race.insert(13, 'superintendent', final_df_discipline_totals['superintendent'], True)
final_df_nypd_contact_race.insert(14, 'expulsions', final_df_discipline_totals['expulsions'], True)

## 7 - MERGE 2 NYPD_CONTACTS_GENDER COLS to NYPD_CONTACTS_RACE
final_df_nypd_contact_race.insert(15, 'female removals or suspensions resulting from incidents where nypd was contacted', final_df_nypd_contact_gender['female removals or suspensions resulting from incidents where nypd was contacted'], True)
final_df_nypd_contact_race.insert(16, 'male removals or suspensions resulting from incidents where nypd was contacted', final_df_nypd_contact_gender['male removals or suspensions resulting from incidents where nypd was contacted'], True)

save_df_to_csv(final_df_nypd_contact_race, 'clean_df', '2018-2017')
# ### --------------
# print(final_df_discipline_totals.head(10))
# print("====")
# print(final_df_nypd_contact_race.head(10))
# print("====")
# print(final_df_nypd_contact_gender.head(10))

# print(xls_2018_discipline.sheet_names)
# print(xls_2018_nypd_contacts.sheet_names)

year is 2018

In [183]:
### 4. Datasets from 2017-2016 
#    -- 3 sheets in total
#    -- Result: 1 dataframe that has all of our relevant columns

xls_2017_discipline = pd.ExcelFile(url_2016_to_2017_student_discipline)
xls_2017_nypd_contacts = pd.ExcelFile(url_2016_to_2017_nypd_contact)

# print(xls_2017_discipline.sheet_names)
# print(xls_2017_nypd_contacts.sheet_names)

df_discipline_totals = pd.read_excel(xls_2018_discipline, index_col=0, sheet_name='Annual Report-- R-P-S TOTALS', engine='openpyxl')
df_nypd_contact_race = pd.read_excel(xls_2018_nypd_contacts, index_col=0, sheet_name='NYPD-SUSP--RACE', engine='openpyxl')
df_nypd_contact_gender = pd.read_excel(xls_2018_nypd_contacts, index_col=0, sheet_name='NYPD-SUSP--GENDER', engine='openpyxl')

## 1 - DROP LAST ROW WITH NAN + TOTAL INFO
final_df_discipline_totals = drop_last_row(df_discipline_totals)
final_df_nypd_contact_race = drop_last_row(df_nypd_contact_race)
final_df_nypd_contact_gender = drop_last_row(df_nypd_contact_gender)

## 2 - LOWER CASE COL NAMES
lower_case_col_names(final_df_discipline_totals)
lower_case_col_names(final_df_nypd_contact_race)
lower_case_col_names(final_df_nypd_contact_gender)

## 3 - CHANGE COL NAMES TO BE MORE DESCRIPTIVE
rename_col_from('location name', 'school_name', final_df_discipline_totals)
rename_col_from('location category', 'school_type', final_df_discipline_totals)
rename_col_from('removals', 'removal', final_df_discipline_totals)

rename_col_from('location name', 'school_name', final_df_nypd_contact_race)
rename_col_from('location category', 'school_type', final_df_nypd_contact_race)

rename_col_from('location name', 'school_name', final_df_nypd_contact_gender)
rename_col_from('location category', 'school_type', final_df_nypd_contact_gender)

## 4 - CHANGE 'R' occurences to int 3
df_tuple = (
    change_r_occurence(
        final_df_nypd_contact_race, 
        final_df_nypd_contact_gender, 
        final_df_discipline_totals, 
        2017)
)
final_df_discipline_totals = df_tuple[2]
final_df_nypd_contact_race = df_tuple[0]
final_df_nypd_contact_gender = df_tuple[1]

## 5 - CHANGE index to unique nums
final_df_discipline_totals.reset_index(inplace=True)
final_df_nypd_contact_race.reset_index(inplace=True)
final_df_nypd_contact_gender.reset_index(inplace=True)

## 6 - MERGE 4 COLS FROM STUDENT_DISCIPLINE DF to NYPD_CONTACTS_RACE
final_df_nypd_contact_race.insert(11, 'principal', final_df_discipline_totals['principal'], True)
final_df_nypd_contact_race.insert(12, 'removal', final_df_discipline_totals['removal'], True)
final_df_nypd_contact_race.insert(13, 'superintendent', final_df_discipline_totals['superintendent'], True)
final_df_nypd_contact_race.insert(14, 'expulsions', final_df_discipline_totals['expulsions'], True)

## 7 - MERGE 2 NYPD_CONTACTS_GENDER COLS to NYPD_CONTACTS_RACE
final_df_nypd_contact_race.insert(15, 'female removals or suspensions resulting from incidents where nypd was contacted', final_df_nypd_contact_gender['female removals or suspensions resulting from incidents where nypd was contacted'], True)
final_df_nypd_contact_race.insert(16, 'male removals or suspensions resulting from incidents where nypd was contacted', final_df_nypd_contact_gender['male removals or suspensions resulting from incidents where nypd was contacted'], True)

save_df_to_csv(final_df_nypd_contact_race, 'clean_df', '2017-2016')

# ### --------------
# print(final_df_discipline_totals.head(4))
# print("====")
# print(final_df_nypd_contact_race.head(4))
# print("====")
# print(final_df_nypd_contact_gender.head(4))

year is 2017

In [188]:
### 5. Datasets from 2016-2015 
#    -- 3 sheets in total
#    -- Result: 1 dataframe that has all of our relevant columns

xls_2016_discipline = pd.ExcelFile(url_2015_to_2016_student_discipline)
xls_2016_nypd_contacts = pd.ExcelFile(url_2015_to_2016_nypd_contact)

# print(xls_2017_discipline.sheet_names)
# print(xls_2017_nypd_contacts.sheet_names)

df_discipline_totals = pd.read_excel(xls_2018_discipline, index_col=0, sheet_name='Annual Report-- R-P-S TOTALS', engine='openpyxl')
df_nypd_contact_race = pd.read_excel(xls_2018_nypd_contacts, index_col=0, sheet_name='NYPD-SUSP--RACE', engine='openpyxl')
df_nypd_contact_gender = pd.read_excel(xls_2018_nypd_contacts, index_col=0, sheet_name='NYPD-SUSP--GENDER', engine='openpyxl')

## 1 - DROP LAST ROW WITH NAN + TOTAL INFO
final_df_discipline_totals = drop_last_row(df_discipline_totals)
final_df_nypd_contact_race = drop_last_row(df_nypd_contact_race)
final_df_nypd_contact_gender = drop_last_row(df_nypd_contact_gender)

## 2 - LOWER CASE COL NAMES
lower_case_col_names(final_df_discipline_totals)
lower_case_col_names(final_df_nypd_contact_race)
lower_case_col_names(final_df_nypd_contact_gender)

## 3 - CHANGE COL NAMES TO BE MORE DESCRIPTIVE
rename_col_from('location name', 'school_name', final_df_discipline_totals)
rename_col_from('location category', 'school_type', final_df_discipline_totals)
rename_col_from('removals', 'removal', final_df_discipline_totals)

rename_col_from('location name', 'school_name', final_df_nypd_contact_race)
rename_col_from('location category', 'school_type', final_df_nypd_contact_race)

rename_col_from('location name', 'school_name', final_df_nypd_contact_gender)
rename_col_from('location category', 'school_type', final_df_nypd_contact_gender)

# 4 - CHANGE 'R' occurences to int 3
df_tuple = (
    change_r_occurence(
        final_df_nypd_contact_race, 
        final_df_nypd_contact_gender, 
        final_df_discipline_totals, 
        2016)
)
final_df_discipline_totals = df_tuple[2]
final_df_nypd_contact_race = df_tuple[0]
final_df_nypd_contact_gender = df_tuple[1]

## 5 - CHANGE index to unique nums
final_df_discipline_totals.reset_index(inplace=True)
final_df_nypd_contact_race.reset_index(inplace=True)
final_df_nypd_contact_gender.reset_index(inplace=True)

## 6 - MERGE 4 COLS FROM STUDENT_DISCIPLINE DF to NYPD_CONTACTS_RACE
final_df_nypd_contact_race.insert(11, 'principal', final_df_discipline_totals['principal'], True)
final_df_nypd_contact_race.insert(12, 'removal', final_df_discipline_totals['removal'], True)
final_df_nypd_contact_race.insert(13, 'superintendent', final_df_discipline_totals['superintendent'], True)
final_df_nypd_contact_race.insert(14, 'expulsions', final_df_discipline_totals['expulsions'], True)

## 7 - MERGE 2 NYPD_CONTACTS_GENDER COLS to NYPD_CONTACTS_RACE
final_df_nypd_contact_race.insert(15, 'female removals or suspensions resulting from incidents where nypd was contacted', final_df_nypd_contact_gender['female removals or suspensions resulting from incidents where nypd was contacted'], True)
final_df_nypd_contact_race.insert(16, 'male removals or suspensions resulting from incidents where nypd was contacted', final_df_nypd_contact_gender['male removals or suspensions resulting from incidents where nypd was contacted'], True)

save_df_to_csv(final_df_nypd_contact_race, 'clean_df', '2016-2015')

# ### --------------
# print(final_df_discipline_totals.head(2))
# print("====")
# print(final_df_nypd_contact_race.head(2))
# print("====")
# print(final_df_nypd_contact_gender.head(2))

year is 2016

In [91]:
# THIS CELL IS FOR 2019-2020

#NOTE: remember to `pip install openpyxl` in a terminal window 
xls = pd.ExcelFile(url_2019_to_2020)
df_race = pd.read_excel(xls, index_col=0, sheet_name='Annual Report--RACE', engine='openpyxl')
df_gender = pd.read_excel(xls,  index_col=0, sheet_name='Annual Report--GENDER', engine='openpyxl')

## -- FIRST AND SECOND SHEET CLEANING ---
# 1 - DROP LAST ROW (which has NAN & and is the total)
final_df_race = df_race.drop(df_race.tail(1).index)
final_df_gender = df_gender.drop(df_gender.tail(1).index)

# 2 - CHANGE COLUMN NAMES
final_df_race.rename(
    columns={
        'Location_Name': 'school_name', 
        'Location_Category_Description': 'school_category',
        'Administrative_District_Code': 'district_code',
        'American Indian/Alaskan Native': 'american_indian_or_alaskan_native',
        'Asian': 'asian',
        'Black': 'black', 
        'Hispanic': 'hispanic', 
        'Multi-Racial': 'multi_racial', 
        'Unknown': 'unknown', 
        'White': 'white',
        'SY1920_STUDENTS_WITH_2_OR_MORE_REMOVALS_SUSPENSIONS': 'students_with_two_or_more_removals_suspensions'
    }, 
    inplace=True
)
final_df_gender.rename(
    columns={
        'Location_Name': 'school_name', 
        'Location_Category_Description': 'school_category',
        'Administrative_District_Code': 'district_code',
        'FEMALE': 'female',
        'MALE': 'male',
        'SY1920_STUDENTS_WITH_2_OR_MORE_REMOVALS_SUSPENSIONS': 'students_with_two_or_more_removals_suspensions'
    },
    inplace=True
)

# 3 - LOWER CASE column 'school_category'
final_df_race['school_category'] = final_df_race['school_category'].str.lower()
final_df_gender['school_category'] = final_df_gender['school_category'].str.lower()

# 4 - CHANGE 'R' in column data to 3.
# NOTE: we arrive to this number because 'R' is used for values between 1-5 (inclusive) but cannot be shown for privacy concerns. 
# As a result, we take the avg of 1+2+3+4+5 => 3
race_cols_with_r_val = ['american_indian_or_alaskan_native', 'asian', 'black', 'hispanic', 'multi_racial', 'unknown', 'white', 'students_with_two_or_more_removals_suspensions'] 
gender_cols_with_r_val = ['female', 'male', 'students_with_two_or_more_removals_suspensions']
final_df_race[race_cols_with_r_val] = final_df_race[race_cols_with_r_val].replace(to_replace={'R': 3})
final_df_gender[gender_cols_with_r_val] = final_df_gender[gender_cols_with_r_val].replace(to_replace={'R': 3})

# 5 - CHANGE all object cols with object type to numeric type
final_df_race[race_cols_with_r_val] = final_df_race[race_cols_with_r_val].apply(pd.to_numeric)

# 6 - CHANGE col 'district_code' type from 
final_df_race['district_code'] = final_df_race['district_code'].astype('int')
final_df_gender['district_code'] = final_df_gender['district_code'].astype('int')

# 7 - CHANGE index to unique nums
final_df_race.reset_index(inplace=True)
final_df_gender.reset_index(inplace=True)
# print(final_df_race)
# print("=====")
# print("=====")
# print(final_df_gender)
final_df_race.to_csv('clean_df_race.csv', encoding='utf-8')
final_df_gender.to_csv('clean_df_gender.csv',  encoding='utf-8')

In [29]:
# THIS CELL IS FOR 2018-2019

#NOTE: remember to `pip install openpyxl` in a terminal window 
xls = pd.ExcelFile(url_2018_to_2019)
df_race = pd.read_excel(xls, index_col=0, sheet_name='2+ STUD--RACE', engine='openpyxl')
df_gender = pd.read_excel(xls,  index_col=0, sheet_name='2+ STUD--GENDER', engine='openpyxl')

## -- FIRST AND SECOND SHEET CLEANING ---
# 1 - DROP LAST ROW (which has NAN & and is the total)
final_df_race = df_race.drop(df_race.tail(1).index)
final_df_gender = df_gender.drop(df_gender.tail(1).index)

# 1.2 - DROP `TOTAL STUDENTS With 2 or More Suspensions or Removals` columns
final_df_race = final_df_race.drop(['TOTAL STUDENTS With 2 or More Suspensions or Removals'], axis=1)
final_df_gender = final_df_gender.drop(['TOTAL STUDENTS With 2 or More Suspensions or Removals'], axis=1)

# 2 - CHANGE COLUMN NAMES
final_df_race.rename(
    columns={
        'LOCATION NAME': 'school_name', 
        'LOCATION CATEGORY': 'school_category',
        'ADMINISTRATIVE DISTRICT': 'district_code',
        'AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals': 'american_indian_or_alaskan_native',
        'ASIAN STUDENTS With 2 or More Suspensions or Removals': 'asian',
        'BLACK STUDENTS With 2 or More Suspensions or Removals': 'black', 
        'HISPANIC STUDENTS With 2 or More Suspensions or Removals': 'hispanic', 
        'MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals': 'multi_racial', 
        'UNKNOWN STUDENTS With 2 or More Suspensions or Removals': 'unknown', 
        'WHITE STUDENTS With 2 or More Suspensions or Removals': 'white',
    }, 
    inplace=True
)
final_df_gender.rename(
    columns={
        'LOCATION NAME': 'school_name', 
        'LOCATION CATEGORY': 'school_category',
        'ADMINISTRATIVE DISTRICT': 'district_code',
        'FEMALE STUDENTS With 2 or More Suspensions or Removals': 'female',
        'MALE STUDENTS With 2 or More Suspensions or Removals': 'male',
    },
    inplace=True
)

# 3 - LOWER CASE column 'school_category'
final_df_race['school_category'] = final_df_race['school_category'].str.lower()
final_df_gender['school_category'] = final_df_gender['school_category'].str.lower()

# 4 - CHANGE 'R' in column data to 3.
# NOTE: we arrive to this number because 'R' is used for values between 1-5 (inclusive) but cannot be shown for privacy concerns. 
# As a result, we take the avg of 1+2+3+4+5 => 3
race_cols_with_r_val = ['american_indian_or_alaskan_native', 'asian', 'black', 'hispanic', 'multi_racial', 'unknown', 'white'] 
gender_cols_with_r_val = ['female', 'male']
final_df_race[race_cols_with_r_val] = final_df_race[race_cols_with_r_val].replace(to_replace={'R': 3})
final_df_gender[gender_cols_with_r_val] = final_df_gender[gender_cols_with_r_val].replace(to_replace={'R': 3})

# 5 - CHANGE col 'district_code' type from 
final_df_race['district_code'] = final_df_race['district_code'].astype('int')
final_df_gender['district_code'] = final_df_gender['district_code'].astype('int')

# 6 - CHANGE index to unique nums
final_df_race.reset_index(inplace=True)
final_df_gender.reset_index(inplace=True)

# print(final_df_race.info())
# print("***********")
# print(final_df_gender.info())

final_df_race.to_csv('clean_df_race_2018_to_2019.csv', encoding='utf-8')
final_df_gender.to_csv('clean_df_gender_2018_to_2019.csv',  encoding='utf-8')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1609 entries, 0 to 1608
Data columns (total 11 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   DBN                                1609 non-null   object
 1   school_name                        1609 non-null   object
 2   school_category                    1609 non-null   object
 3   district_code                      1609 non-null   int64
 4   american_indian_or_alaskan_native  1609 non-null   int64
 5   asian                              1609 non-null   int64
 6   black                              1609 non-null   int64
 7   hispanic                           1609 non-null   int64
 8   white                              1609 non-null   int64
 9   multi_racial                       1609 non-null   int64
 10  unknown                            1609 non-null   int64
dtypes: int64(8), object(3)
memory usage: 138.4+ KB
None
***********
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1609 entries, 0 to 1608
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DBN              1609 non-null   object
 1   school_name      1609 non-null   object
 2   school_category  1609 non-null   object
 3   district_code    1609 non-null   int64
 4   female           1609 non-null   int64
 5   male             1609 non-null   int64
dtypes: int64(3), object(3)
memory usage: 75.5+ KB
None

In [42]:
# THIS CELL IS FOR 2017-2018

#NOTE: remember to `pip install openpyxl` in a terminal window 
xls = pd.ExcelFile(url_2017_to_2018)
df_race = pd.read_excel(xls, index_col=0, sheet_name='2+ STUD--RACE', engine='openpyxl')
df_gender = pd.read_excel(xls,  index_col=0, sheet_name='2+ STUD--GENDER', engine='openpyxl')

## -- FIRST AND SECOND SHEET CLEANING ---
# 1 - DROP LAST ROW (which has NAN & and is the total)
final_df_race = df_race.drop(df_race.tail(1).index)
final_df_gender = df_gender.drop(df_gender.tail(1).index)

# 2 - CHANGE COLUMN NAMES
final_df_race.rename(
    columns={
        'LOCATION NAME': 'school_name', 
        'LOCATION CATEGORY': 'school_category',
        'ADMINISTRATIVE DISTRICT': 'district_code',
        'AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals': 'american_indian_or_alaskan_native',
        'ASIAN STUDENTS With 2 or More Suspensions or Removals': 'asian',
        'BLACK STUDENTS With 2 or More Suspensions or Removals': 'black', 
        'HISPANIC STUDENTS With 2 or More Suspensions or Removals': 'hispanic', 
        'MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals': 'multi_racial', 
        'UNKNOWN STUDENTS With 2 or More Suspensions or Removals': 'unknown', 
        'WHITE STUDENTS With 2 or More Suspensions or Removals': 'white',
        'TOTAL STUDENTS With 2 or More Suspensions or Removals': 'total_students_with_two_or_more_removals_suspensions'
    }, 
    inplace=True
)
final_df_gender.rename(
    columns={
        'LOCATION NAME': 'school_name', 
        'LOCATION CATEGORY': 'school_category',
        'ADMINISTRATIVE DISTRICT': 'district_code',
        'FEMALE STUDENTS With 2 or More Suspensions or Removals': 'female',
        'MALE STUDENTS With 2 or More Suspensions or Removals': 'male',
        'TOTAL STUDENTS With 2 or More Suspensions or Removals': 'total_students_with_two_or_more_removals_suspensions'
    },
    inplace=True
)

# 3 - LOWER CASE column 'school_category'
final_df_race['school_category'] = final_df_race['school_category'].str.lower()
final_df_gender['school_category'] = final_df_gender['school_category'].str.lower()

# 4 - CHANGE 'R' in column data to 3.
# NOTE: we arrive to this number because 'R' is used for values between 1-5 (inclusive) but cannot be shown for privacy concerns. 
# As a result, we take the avg of 1+2+3+4+5 => 3
race_cols_with_r_val = ['american_indian_or_alaskan_native', 'asian', 'black', 'hispanic', 'multi_racial', 'unknown', 'white', 'total_students_with_two_or_more_removals_suspensions'] 
gender_cols_with_r_val = ['female', 'male', 'total_students_with_two_or_more_removals_suspensions']
final_df_race[race_cols_with_r_val] = final_df_race[race_cols_with_r_val].replace(to_replace={'R': 3})
final_df_gender[gender_cols_with_r_val] = final_df_gender[gender_cols_with_r_val].replace(to_replace={'R': 3})

# 5 - CHANGE col 'district_code' type from float to int
final_df_race['district_code'] = final_df_race['district_code'].astype('int')
final_df_gender['district_code'] = final_df_gender['district_code'].astype('int')

# 6 - CHANGE col 'total_students_with_two_or_more_removals_suspensions' type from obj to int
final_df_race['total_students_with_two_or_more_removals_suspensions'] = final_df_race['total_students_with_two_or_more_removals_suspensions'].astype('int')
final_df_gender['total_students_with_two_or_more_removals_suspensions'] = final_df_gender['total_students_with_two_or_more_removals_suspensions'].astype('int') 

# 7 - CHANGE index to unique nums
final_df_race.reset_index(inplace=True)
final_df_gender.reset_index(inplace=True)

# print(final_df_race)
# print(final_df_gender)

final_df_race.to_csv('clean_df_race_2017_to_2018.csv', encoding='utf-8')
final_df_gender.to_csv('clean_df_gender_2017_to_2018.csv',  encoding='utf-8')

In [56]:
# THIS CELL IS FOR 2016-2017

#NOTE: remember to `pip install openpyxl` in a terminal window 
xls = pd.ExcelFile(url_2016_to_2017)
df_race = pd.read_excel(xls, index_col=0, sheet_name='2+ STUD--RACE', engine='openpyxl')
df_gender = pd.read_excel(xls,  index_col=0, sheet_name='2+ STUD--GENDER', engine='openpyxl')

## -- FIRST AND SECOND SHEET CLEANING ---
# 1 - DROP LAST ROW (which has NAN & and is the total)
final_df_race = df_race.drop(df_race.tail(1).index)
final_df_gender = df_gender.drop(df_gender.tail(1).index)

# 2 - CHANGE COLUMN NAMES
final_df_race.rename(
    columns={
        'LOCATION NAME': 'school_name', 
        'LOCATION CATEGORY': 'school_category',
        'ADMINISTRATIVE DISTRICT': 'district_code',
        'AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals': 'american_indian_or_alaskan_native',
        'ASIAN STUDENTS With 2 or More Suspensions or Removals': 'asian',
        'BLACK STUDENTS With 2 or More Suspensions or Removals': 'black', 
        'HISPANIC STUDENTS With 2 or More Suspensions or Removals': 'hispanic', 
        'MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals': 'multi_racial', 
        'UNKNOWN STUDENTS With 2 or More Suspensions or Removals': 'unknown', 
        'WHITE STUDENTS With 2 or More Suspensions or Removals': 'white',
        'TOTAL STUDENTS With 2 or More Suspensions or Removals': 'total_students_with_two_or_more_removals_suspensions'
    }, 
    inplace=True
)
final_df_gender.rename(
    columns={
        'LOCATION NAME': 'school_name', 
        'LOCATION CATEGORY': 'school_category',
        'ADMINISTRATIVE DISTRICT': 'district_code',
        'FEMALE STUDENTS With 2 or More Suspensions or Removals': 'female',
        'MALE STUDENTS With 2 or More Suspensions or Removals': 'male',
        'TOTAL STUDENTS With 2 or More Suspensions or Removals': 'total_students_with_two_or_more_removals_suspensions'
    },
    inplace=True
)

# 3 - LOWER CASE column 'school_category'
final_df_race['school_category'] = final_df_race['school_category'].str.lower()
final_df_gender['school_category'] = final_df_gender['school_category'].str.lower()

# 4 - CHANGE 'R' in column data to 3.
# NOTE: we arrive to this number because 'R' is used for values between 1-5 (inclusive) but cannot be shown for privacy concerns. 
# As a result, we take the avg of 1+2+3+4+5 => 3
race_cols_with_r_val = ['american_indian_or_alaskan_native', 'asian', 'black', 'hispanic', 'multi_racial', 'unknown', 'white', 'total_students_with_two_or_more_removals_suspensions'] 
gender_cols_with_r_val = ['female', 'male', 'total_students_with_two_or_more_removals_suspensions']
final_df_race[race_cols_with_r_val] = final_df_race[race_cols_with_r_val].replace(to_replace={'R': 3})
final_df_gender[gender_cols_with_r_val] = final_df_gender[gender_cols_with_r_val].replace(to_replace={'R': 3})

# 5 - CHANGE col 'district_code' type from float to int
final_df_race['district_code'] = final_df_race['district_code'].astype('int')
final_df_gender['district_code'] = final_df_gender['district_code'].astype('int')

# 6 - CHANGE index to unique nums
final_df_race.reset_index(inplace=True)
final_df_gender.reset_index(inplace=True)

# print(final_df_race)
# print(final_df_gender)

final_df_race.to_csv('clean_df_race_2016_to_2017.csv', encoding='utf-8')
final_df_gender.to_csv('clean_df_gender_2016_to_2017.csv',  encoding='utf-8')

In [72]:
# THIS CELL IS FOR 2015-2016

#NOTE: remember to `pip install openpyxl` in a terminal window 
xls = pd.ExcelFile(url_2015_to_2016)
df_race = pd.read_excel(xls, index_col=0, sheet_name='2+ STUD--RACE', engine='openpyxl')
df_gender = pd.read_excel(xls,  index_col=0, sheet_name='2+ STUD--GENDER', engine='openpyxl')

## -- FIRST AND SECOND SHEET CLEANING ---
# 1 - DROP LAST ROW (which has NAN & and is the total)
final_df_race = df_race.drop(df_race.tail(1).index)
final_df_gender = df_gender.drop(df_gender.tail(1).index)

# 2 - DROP EMPTY COLUMNS 
final_df_race = final_df_race.dropna(how='all', axis=1)

# 3 - CHANGE COLUMN NAMES
final_df_race.rename(
    columns={
        'LOCATION NAME': 'school_name', 
        'LOCATION CATEGORY': 'school_category',
        'ADMINISTRATIVE DISTRICT': 'district_code',
        'AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals': 'american_indian_or_alaskan_native',
        'ASIAN STUDENTS With 2 or More Suspensions or Removals': 'asian',
        'BLACK STUDENTS With 2 or More Suspensions or Removals': 'black', 
        'HISPANIC STUDENTS With 2 or More Suspensions or Removals': 'hispanic', 
        'MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals': 'multi_racial', 
        'UNKNOWN STUDENTS With 2 or More Suspensions or Removals': 'unknown', 
        'WHITE STUDENTS With 2 or More Suspensions or Removals': 'white',
        'TOTAL STUDENTS With 2 or More Suspensions or Removals': 'total_students_with_two_or_more_removals_suspensions'
    }, 
    inplace=True
)
final_df_gender.rename(
    columns={
        'LOCATION NAME': 'school_name', 
        'LOCATION CATEGORY': 'school_category',
        'ADMINISTRATIVE DISTRICT': 'district_code',
        'FEMALE STUDENTS With 2 or More Suspensions or Removals': 'female',
        'MALE STUDENTS With 2 or More Suspensions or Removals': 'male',
        'TOTAL STUDENTS With 2 or More Suspensions or Removals': 'total_students_with_two_or_more_removals_suspensions'
    },
    inplace=True
)

# 4 - LOWER CASE column 'school_category'
final_df_race['school_category'] = final_df_race['school_category'].str.lower()
final_df_gender['school_category'] = final_df_gender['school_category'].str.lower()

# 5 - CHANGE '*' in column data to 3.
# NOTE: we arrive to this number because 'R' is used for values between 1-5 (inclusive) but cannot be shown for privacy concerns. 
# As a result, we take the avg of 1+2+3+4+5 => 3
race_cols_with_r_val = ['american_indian_or_alaskan_native', 'asian', 'black', 'hispanic', 'multi_racial', 'unknown', 'white', 'total_students_with_two_or_more_removals_suspensions'] 
gender_cols_with_r_val = ['female', 'male', 'total_students_with_two_or_more_removals_suspensions']
final_df_race[race_cols_with_r_val] = final_df_race[race_cols_with_r_val].replace(to_replace={'*': 3})
final_df_gender[gender_cols_with_r_val] = final_df_gender[gender_cols_with_r_val].replace(to_replace={'*': 3})

# 6 - CHANGE col 'district_code' type from float to int
final_df_race['district_code'] = final_df_race['district_code'].astype('int')
final_df_gender['district_code'] = final_df_gender['district_code'].astype('int')

# 7 - CHANGE index to unique nums
final_df_race.reset_index(inplace=True)
final_df_gender.reset_index(inplace=True)

print(final_df_race)
print(final_df_gender)

final_df_race.to_csv('clean_df_race_2015_to_2016.csv', encoding='utf-8')
final_df_gender.to_csv('clean_df_gender_2015_to_2016.csv',  encoding='utf-8')

         DBN                     school_name  school_category  district_code  \
0     01M015       P.S. 015 Roberto Clemente       elementary              1
1     01M019             P.S. 019 Asher Levy       elementary              1
2     01M020            P.S. 020 Anna Silver       elementary              1
3     01M034  P.S. 034 Franklin D. Roosevelt              k-8              1
4     01M063       The STAR Academy - P.S.63       elementary              1
...      ...                             ...              ...            ...
1737  79M984                            LYFE         ungraded             79
1738  79Q344              East River Academy      high school             79
1739  79Q950          Pathways to Graduation      high school             79
1740  79X490                 Phoenix Academy      high school             79
1741  79X695                Passages Academy  k-12 all grades             79

      american_indian_or_alaskan_native  asian  black  hispanic  white  \
0                                     3      3      3         3      3
1                                     3      3      3         3      3
2                                     3      3      3         3      3
3                                     3      3      3         3      3
4                                     3      3      3         3      3
...                                 ...    ...    ...       ...    ...
1737                                  3      3      3         3      3
1738                                  3      3      3         3      3
1739                                  3      3      3         3      3
1740                                  3      3      3         3      3
1741                                  3      3      3         3      3

      multi_racial  unknown  \
0                3        3
1                3        3
2                3        3
3                3        3
4                3        3
...            ...      ...
1737             3        3
1738             3        3
1739             3        3
1740             3        3
1741             3        3

      total_students_with_two_or_more_removals_suspensions
0                                                     3
1                                                     3
2                                                     3
3                                                    14
4                                                     6
...                                                 ...
1737                                                  3
1738                                                  3
1739                                                  3
1740                                                  3
1741                                                  3

[1742 rows x 12 columns]
         DBN                     school_name  school_category  district_code  \
0     01M015       P.S. 015 Roberto Clemente       elementary              1
1     01M019             P.S. 019 Asher Levy       elementary              1
2     01M020            P.S. 020 Anna Silver       elementary              1
3     01M034  P.S. 034 Franklin D. Roosevelt              k-8              1
4     01M063       The STAR Academy - P.S.63       elementary              1
...      ...                             ...              ...            ...
1737  79M984                            LYFE         ungraded             79
1738  79Q344              East River Academy      high school             79
1739  79Q950          Pathways to Graduation      high school             79
1740  79X490                 Phoenix Academy      high school             79
1741  79X695                Passages Academy  k-12 all grades             79

      female  male  total_students_with_two_or_more_removals_suspensions
0          3     3                                                  3
1          3     3                                                  3
2          3     3                                                  3
3          8     6                                                 14
4          3     3                                                  6
...      ...   ...                                                ...
1737       3     3                                                  3
1738       3     3                                                  3
1739       3     3                                                  3
1740       3     3                                                  3
1741       3     3                                                  3

[1742 rows x 7 columns]