In [2]:
!pip install -r requirements.txt

Requirement already satisfied: numpy in /opt/conda/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.20.2)
Requirement already satisfied: pandas in /opt/conda/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (1.2.4)
Requirement already satisfied: sklearn in /opt/conda/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (0.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.8/site-packages (from pandas->-r requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.8/site-packages (from pandas->-r requirements.txt (line 2)) (2021.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas->-r requirements.txt (line 2)) (1.15.0)
Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.8/site-packages (from sklearn->-r requirements.txt (line 3)) (0.24.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.8/site-packages (from scikit-learn->sklearn->-r requirements.txt (line 3)) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /opt/conda/lib/python3.8/site-packages (from scikit-learn->sklearn->-r requirements.txt (line 3)) (1.0.1)
Requirement already satisfied: scipy>=0.19.1 in /opt/conda/lib/python3.8/site-packages (from scikit-learn->sklearn->-r requirements.txt (line 3)) (1.6.3)

In [3]:
import numpy as np
import pandas as pd
import sklearn

In [4]:
df = pd.read_csv('data/demographic-snapshot-2016-17-to-2020-21-public-burough.csv')
df.head()

,Borough,Year,Total Enrollment,Grade 3K+PK (Half Day & Full Day),Grade K,Grade 1,Grade 2,Grade 3,Grade 4,Grade 5,...,% White,# Missing Race/Ethnicity Data,% Missing Race/Ethnicity Data,# Students with Disabilities,% Students with Disabilities,# English Language Learners,% English Language Learners,# Poverty,% Poverty,Economic Need Index
0,Bronx,2016-17,"241,776","14,825","17,974","19,579","19,611","18,943","18,505","17,824",...,4.3%,725,0.3%,"55,462",22.9%,"41,129",17.0%,"197,520",81.7%,77.4%
1,Bronx,2017-18,"239,955","14,948","17,812","18,598","19,008","18,940","18,535","18,173",...,4.4%,436,0.2%,"55,719",23.2%,"41,316",17.2%,"208,334",86.8%,85.7%
2,Bronx,2018-19,"236,267","15,105","17,259","18,071","17,962","18,318","18,426","18,026",...,4.3%,461,0.2%,"55,847",23.6%,"40,055",17.0%,"203,040",85.9%,85.4%
3,Bronx,2019-20,"235,448","17,990","17,103","17,680","17,598","17,462","17,981","18,216",...,4.2%,"1,367",0.6%,"54,899",23.3%,"37,509",15.9%,"202,976",86.2%,86.8%
4,Bronx,2020-21,"227,224","14,769","15,468","16,863","17,031","17,016","16,906","17,579",...,4.2%,937,0.4%,"53,144",23.4%,"37,190",16.4%,"194,432",85.6%,85.8%

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 42 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Borough                            25 non-null     object
 1   Year                               25 non-null     object
 2   Total Enrollment                   25 non-null     object
 3   Grade 3K+PK (Half Day & Full Day)  25 non-null     object
 4   Grade K                            25 non-null     object
 5   Grade 1                            25 non-null     object
 6   Grade 2                            25 non-null     object
 7   Grade 3                            25 non-null     object
 8   Grade 4                            25 non-null     object
 9   Grade 5                            25 non-null     object
 10  Grade 6                            25 non-null     object
 11  Grade 7                            25 non-null     object
 12  Grade 8                            25 non-null     object
 13  Grade 9                            25 non-null     object
 14  Grade 10                           25 non-null     object
 15  Grade 11                           25 non-null     object
 16  Grade 12                           25 non-null     object
 17  # Female                           25 non-null     object
 18  % Female                           25 non-null     object
 19  # Male                             25 non-null     object
 20  % Male                             25 non-null     object
 21  # Asian                            25 non-null     object
 22  % Asian                            25 non-null     object
 23  # Black                            25 non-null     object
 24  % Black                            25 non-null     object
 25  # Hispanic                         25 non-null     object
 26  % Hispanic                         25 non-null     object
 27  # Multi-Racial                     25 non-null     object
 28  % Multi-Racial                     25 non-null     object
 29  # Native American                  25 non-null     object
 30  % Native American                  25 non-null     object
 31  # White                            25 non-null     object
 32  % White                            25 non-null     object
 33  # Missing Race/Ethnicity Data      25 non-null     object
 34  % Missing Race/Ethnicity Data      25 non-null     object
 35  # Students with Disabilities       25 non-null     object
 36  % Students with Disabilities       25 non-null     object
 37  # English Language Learners        25 non-null     object
 38  % English Language Learners        25 non-null     object
 39  # Poverty                          25 non-null     object
 40  % Poverty                          25 non-null     object
 41  Economic Need Index                25 non-null     object
dtypes: object(42)
memory usage: 8.3+ KB

In [14]:
df['Grade K'] = df['Grade K'].str.split(',').str.join('').astype(int)
df['Grade 1'] = df['Grade 1'].str.split(',').str.join('').astype(int)
df['Grade 2'] = df['Grade 2'].str.split(',').str.join('').astype(int)
df['Grade 3'] = df['Grade 3'].str.split(',').str.join('').astype(int)
df['Grade 4'] = df['Grade 4'].str.split(',').str.join('').astype(int)
df['Grade 5'] = df['Grade 5'].str.split(',').str.join('').astype(int)
df['Grade 6'] = df['Grade 6'].str.split(',').str.join('').astype(int)
df['Grade 7'] = df['Grade 7'].str.split(',').str.join('').astype(int)
df['Grade 8'] = df['Grade 8'].str.split(',').str.join('').astype(int)
df['Grade 9'] = df['Grade 9'].str.split(',').str.join('').astype(int)
df['Grade 10'] = df['Grade 10'].str.split(',').str.join('').astype(int)
df['Grade 11'] = df['Grade 11'].str.split(',').str.join('').astype(int)
df['Grade 12'] = df['Grade 12'].str.split(',').str.join('').astype(int)
df['Total Enrollment'] = df['Total Enrollment'].str.split(',').str.join('').astype(int)
df['Grade 3K+PK (Half Day & Full Day)'] = df['Grade 3K+PK (Half Day & Full Day)'].str.split(',').str.join('').astype(int)

In [7]:
df.shape

(25, 42)

In [8]:
df.isnull().sum()

Borough                              0
Year                                 0
Total Enrollment                     0
Grade 3K+PK (Half Day & Full Day)    0
Grade K                              0
Grade 1                              0
Grade 2                              0
Grade 3                              0
Grade 4                              0
Grade 5                              0
Grade 6                              0
Grade 7                              0
Grade 8                              0
Grade 9                              0
Grade 10                             0
Grade 11                             0
Grade 12                             0
# Female                             0
% Female                             0
# Male                               0
% Male                               0
# Asian                              0
% Asian                              0
# Black                              0
% Black                              0
# Hispanic                           0
% Hispanic                           0
# Multi-Racial                       0
% Multi-Racial                       0
# Native American                    0
% Native American                    0
# White                              0
% White                              0
# Missing Race/Ethnicity Data        0
% Missing Race/Ethnicity Data        0
# Students with Disabilities         0
% Students with Disabilities         0
# English Language Learners          0
% English Language Learners          0
# Poverty                            0
% Poverty                            0
Economic Need Index                  0
dtype: int64

In [15]:
df.dtypes

Year                                 object
Total Enrollment                      int64
Grade 3K+PK (Half Day & Full Day)     int64
Grade K                               int64
Grade 1                               int64
Grade 2                               int64
Grade 3                               int64
Grade 4                               int64
Grade 5                               int64
Grade 6                               int64
Grade 7                               int64
Grade 8                               int64
Grade 9                               int64
Grade 10                              int64
Grade 11                              int64
Grade 12                              int64
# Female                             object
% Female                             object
# Male                               object
% Male                               object
# Asian                              object
% Asian                              object
# Black                              object
% Black                              object
# Hispanic                           object
% Hispanic                           object
# Multi-Racial                       object
% Multi-Racial                       object
# Native American                    object
% Native American                    object
# White                              object
% White                              object
# Missing Race/Ethnicity Data        object
% Missing Race/Ethnicity Data        object
# Students with Disabilities         object
% Students with Disabilities         object
# English Language Learners          object
% English Language Learners          object
# Poverty                            object
% Poverty                            object
Economic Need Index                  object
dtype: object

In [9]:
df = pd.read_csv('data/demographic-snapshot-2016-17-to-2020-21-public-burough.csv', 
                 index_col=0, parse_dates=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, Bronx to Staten Island
Data columns (total 41 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Year                               25 non-null     object
 1   Total Enrollment                   25 non-null     object
 2   Grade 3K+PK (Half Day & Full Day)  25 non-null     object
 3   Grade K                            25 non-null     object
 4   Grade 1                            25 non-null     object
 5   Grade 2                            25 non-null     object
 6   Grade 3                            25 non-null     object
 7   Grade 4                            25 non-null     object
 8   Grade 5                            25 non-null     object
 9   Grade 6                            25 non-null     object
 10  Grade 7                            25 non-null     object
 11  Grade 8                            25 non-null     object
 12  Grade 9                            25 non-null     object
 13  Grade 10                           25 non-null     object
 14  Grade 11                           25 non-null     object
 15  Grade 12                           25 non-null     object
 16  # Female                           25 non-null     object
 17  % Female                           25 non-null     object
 18  # Male                             25 non-null     object
 19  % Male                             25 non-null     object
 20  # Asian                            25 non-null     object
 21  % Asian                            25 non-null     object
 22  # Black                            25 non-null     object
 23  % Black                            25 non-null     object
 24  # Hispanic                         25 non-null     object
 25  % Hispanic                         25 non-null     object
 26  # Multi-Racial                     25 non-null     object
 27  % Multi-Racial                     25 non-null     object
 28  # Native American                  25 non-null     object
 29  % Native American                  25 non-null     object
 30  # White                            25 non-null     object
 31  % White                            25 non-null     object
 32  # Missing Race/Ethnicity Data      25 non-null     object
 33  % Missing Race/Ethnicity Data      25 non-null     object
 34  # Students with Disabilities       25 non-null     object
 35  % Students with Disabilities       25 non-null     object
 36  # English Language Learners        25 non-null     object
 37  % English Language Learners        25 non-null     object
 38  # Poverty                          25 non-null     object
 39  % Poverty                          25 non-null     object
 40  Economic Need Index                25 non-null     object
dtypes: object(41)
memory usage: 8.2+ KB

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, Bronx to Staten Island
Data columns (total 41 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Year                               25 non-null     object
 1   Total Enrollment                   25 non-null     object
 2   Grade 3K+PK (Half Day & Full Day)  25 non-null     object
 3   Grade K                            25 non-null     object
 4   Grade 1                            25 non-null     object
 5   Grade 2                            25 non-null     object
 6   Grade 3                            25 non-null     object
 7   Grade 4                            25 non-null     object
 8   Grade 5                            25 non-null     object
 9   Grade 6                            25 non-null     object
 10  Grade 7                            25 non-null     object
 11  Grade 8                            25 non-null     object
 12  Grade 9                            25 non-null     object
 13  Grade 10                           25 non-null     object
 14  Grade 11                           25 non-null     object
 15  Grade 12                           25 non-null     object
 16  # Female                           25 non-null     object
 17  % Female                           25 non-null     object
 18  # Male                             25 non-null     object
 19  % Male                             25 non-null     object
 20  # Asian                            25 non-null     object
 21  % Asian                            25 non-null     object
 22  # Black                            25 non-null     object
 23  % Black                            25 non-null     object
 24  # Hispanic                         25 non-null     object
 25  % Hispanic                         25 non-null     object
 26  # Multi-Racial                     25 non-null     object
 27  % Multi-Racial                     25 non-null     object
 28  # Native American                  25 non-null     object
 29  % Native American                  25 non-null     object
 30  # White                            25 non-null     object
 31  % White                            25 non-null     object
 32  # Missing Race/Ethnicity Data      25 non-null     object
 33  % Missing Race/Ethnicity Data      25 non-null     object
 34  # Students with Disabilities       25 non-null     object
 35  % Students with Disabilities       25 non-null     object
 36  # English Language Learners        25 non-null     object
 37  % English Language Learners        25 non-null     object
 38  # Poverty                          25 non-null     object
 39  % Poverty                          25 non-null     object
 40  Economic Need Index                25 non-null     object
dtypes: object(41)
memory usage: 8.2+ KB

In [11]:
df.head()

,Year,Total Enrollment,Grade 3K+PK (Half Day & Full Day),Grade K,Grade 1,Grade 2,Grade 3,Grade 4,Grade 5,Grade 6,...,% White,# Missing Race/Ethnicity Data,% Missing Race/Ethnicity Data,# Students with Disabilities,% Students with Disabilities,# English Language Learners,% English Language Learners,# Poverty,% Poverty,Economic Need Index
Borough,,,,,,,,,,,,,,,,,,,,,
Bronx,2016-17,"241,776","14,825","17,974","19,579","19,611","18,943","18,505","17,824","17,207",...,4.3%,725,0.3%,"55,462",22.9%,"41,129",17.0%,"197,520",81.7%,77.4%
Bronx,2017-18,"239,955","14,948","17,812","18,598","19,008","18,940","18,535","18,173","17,152",...,4.4%,436,0.2%,"55,719",23.2%,"41,316",17.2%,"208,334",86.8%,85.7%
Bronx,2018-19,"236,267","15,105","17,259","18,071","17,962","18,318","18,426","18,026","17,405",...,4.3%,461,0.2%,"55,847",23.6%,"40,055",17.0%,"203,040",85.9%,85.4%
Bronx,2019-20,"235,448","17,990","17,103","17,680","17,598","17,462","17,981","18,216","17,498",...,4.2%,"1,367",0.6%,"54,899",23.3%,"37,509",15.9%,"202,976",86.2%,86.8%
Bronx,2020-21,"227,224","14,769","15,468","16,863","17,031","17,016","16,906","17,579","17,401",...,4.2%,937,0.4%,"53,144",23.4%,"37,190",16.4%,"194,432",85.6%,85.8%

In [16]:
df.to_csv('data/clean_demographic_snapshot_burough.csv', encoding='utf-8')