In [2]:
!pip install -r requirements.txt

Requirement already satisfied: numpy in /opt/conda/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.20.2)
Requirement already satisfied: pandas in /opt/conda/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (1.2.4)
Collecting sklearn
  Using cached sklearn-0.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.8/site-packages (from pandas->-r requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.8/site-packages (from pandas->-r requirements.txt (line 2)) (2021.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas->-r requirements.txt (line 2)) (1.15.0)
Collecting scikit-learn
  Using cached scikit_learn-0.24.2-cp38-cp38-manylinux2010_x86_64.whl (24.9 MB)
Collecting scipy>=0.19.1
  Using cached scipy-1.6.3-cp38-cp38-manylinux1_x86_64.whl (27.2 MB)
Collecting joblib>=0.11
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn, sklearn
Successfully installed joblib-1.0.1 scikit-learn-0.24.2 scipy-1.6.3 sklearn-0.0 threadpoolctl-2.1.0

In [3]:
import sklearn
import numpy as np
import pandas as pd

In [4]:
df_q1= pd.read_csv('data/ssa-report-pct-1q-2020.csv')
df_q2 = pd.read_csv('data/ssa-report-pct-2q-2020.csv')
df_q3 = pd.read_csv('data/ssa-report-pct-3q-2020.csv')
df_q4 = pd.read_csv('data/ssa-report-pct-4q-2020.csv')

/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (1,2,3,5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
df_q1

      Pct Intervention Type     Restraints Gender   Age                Race
0       1          Arrested          Metal      M  17.0      White Hispanic
1       1   Child in Crisis  No Restraints      F  17.0  Asian/Pacific Isl.
2       1   Child in Crisis  No Restraints      F  16.0  Asian/Pacific Isl.
3       1   Child in Crisis  No Restraints      M  17.0              Arabic
4       1   Child in Crisis          Metal      M  17.0  Asian/Pacific Isl.
...   ...               ...            ...    ...   ...                 ...
3286  123         Mitigated  No Restraints      M  17.0      Black Hispanic
3287  123         Mitigated  No Restraints      M  15.0               White
3288  123         Mitigated  No Restraints      M  14.0               White
3289  123         Mitigated  No Restraints      F  15.0               White
3290  123         Mitigated  No Restraints      F  15.0               White

[3291 rows x 6 columns]

In [6]:
df_q2

      Pct Intervention Type     Restraints Gender   Age                Race
0    79.0   Juvenile Report  No Restraints      M  11.0               Black
1    79.0   Juvenile Report  No Restraints      M  10.0               Black
2    83.0          Arrested          Metal      M  25.0      White Hispanic
3    83.0          Arrested          Metal      M  20.0      White Hispanic
4    83.0          Arrested          Metal      M  21.0      White Hispanic
5    83.0          Arrested          Metal      M  22.0      White Hispanic
6    70.0          Arrested          Metal      M  19.0      White Hispanic
7    70.0   Juvenile Report  No Restraints      M  17.0  Asian/Pacific Isl.
8    90.0          Arrested          Metal      M  22.0               Black
9    70.0          Arrested          Metal      M  14.0      White Hispanic
10    7.0          Arrested  No Restraints      M  28.0  Asian/Pacific Isl.
11   25.0         Mitigated  No Restraints      F   NaN               Black
12   25.0         Mitigated  No Restraints      F   NaN               Black
13  122.0         Mitigated  No Restraints      F   8.0               White
14  122.0         Mitigated  No Restraints      F   8.0               White
15   42.0          Arrested          Metal      M  15.0               Black
16   42.0          Arrested          Metal      M  16.0               Black
17   42.0          Arrested          Metal      M  13.0      Black Hispanic
18   42.0          Arrested          Metal      M  17.0               Black
19   81.0   Child in Crisis  No Restraints      M   9.0               Black
20    9.0   Child in Crisis  No Restraints      M  14.0      White Hispanic
21    9.0   Child in Crisis  No Restraints      M  14.0      Black Hispanic
22   44.0   Child in Crisis  No Restraints      M  11.0               Black
23    NaN               NaN            NaN    NaN   NaN                 NaN
24    NaN               NaN            NaN    NaN   NaN                 NaN
25    NaN               NaN            NaN    NaN   NaN                 NaN
26    NaN               NaN            NaN    NaN   NaN                 NaN
27    NaN               NaN            NaN    NaN   NaN                 NaN
28    NaN               NaN            NaN    NaN   NaN                 NaN
29    NaN               NaN            NaN    NaN   NaN                 NaN
30    NaN               NaN            NaN    NaN   NaN                 NaN
31    NaN               NaN            NaN    NaN   NaN                 NaN
32    NaN               NaN            NaN    NaN   NaN                 NaN
33    NaN               NaN            NaN    NaN   NaN                 NaN
34    NaN               NaN            NaN    NaN   NaN                 NaN
35    NaN               NaN            NaN    NaN   NaN                 NaN
36    NaN               NaN            NaN    NaN   NaN                 NaN

In [7]:
df_q3

          Pct Intervention     Restraints Gender   Age            Race
0        81.0    Mitigated  No Restraints      F  13.0           Black
1        81.0    Mitigated         Velcro      M   9.0           Black
2        62.0    Mitigated  No Restraints      M  30.0           Black
3         9.0    Mitigated  No Restraints      M  14.0  Black Hispanic
4         9.0    Mitigated  No Restraints      M  14.0  White Hispanic
...       ...          ...            ...    ...   ...             ...
1048568   NaN          NaN            NaN    NaN   NaN             NaN
1048569   NaN          NaN            NaN    NaN   NaN             NaN
1048570   NaN          NaN            NaN    NaN   NaN             NaN
1048571   NaN          NaN            NaN    NaN   NaN             NaN
1048572   NaN          NaN            NaN    NaN   NaN             NaN

[1048573 rows x 6 columns]

In [8]:
df_q3 = df_q3.dropna(subset=["Pct"])

In [9]:
df_q3

      Pct     Intervention     Restraints Gender   Age            Race
0    81.0        Mitigated  No Restraints      F  13.0           Black
1    81.0        Mitigated         Velcro      M   9.0           Black
2    62.0        Mitigated  No Restraints      M  30.0           Black
3     9.0        Mitigated  No Restraints      M  14.0  Black Hispanic
4     9.0        Mitigated  No Restraints      M  14.0  White Hispanic
5    25.0        Mitigated  No Restraints      F  20.0           Black
6    34.0        Mitigated  No Restraints      M   NaN  White Hispanic
7    18.0        Mitigated  No Restraints      M  14.0  White Hispanic
8    18.0        Mitigated  No Restraints      M  14.0           Black
9    18.0        Mitigated  No Restraints      M  14.0           Black
10  109.0          Summons  No Restraints      M  66.0  White Hispanic
11  113.0         Arrested          Metal      M  15.0           Black
12  113.0         Arrested          Metal      M  16.0           Black
13  123.0         Arrested          Metal      F  58.0           White
14  121.0        Mitigated  No Restraints      F   8.0           Black
15   45.0        Mitigated  No Restraints      F  12.0  Black Hispanic
16   45.0        Mitigated  No Restraints      M  14.0  Black Hispanic
17   45.0        Mitigated  No Restraints      M  12.0  Black Hispanic
18   49.0        Mitigated  No Restraints      M  15.0  White Hispanic
19   46.0         Arrested          Metal      M  53.0  Black Hispanic
20   79.0  Child in Crisis  No Restraints      F  16.0  Black Hispanic
21    9.0  Child in Crisis         Velcro      M  10.0  White Hispanic
22    9.0  Child in Crisis  No Restraints      M  10.0  White Hispanic
23    6.0  Child in Crisis  No Restraints      F  14.0           Black
24  110.0  Child in Crisis  No Restraints      M  20.0           Black

In [10]:
df_q3 = df_q3.rename(columns = {"Intervention":"Intervention Type"})

In [11]:
df_q4

          Pct Intervention Type     Restraints Gender   Age      Race
0        81.0   Juvenile Report  No Restraints      M  14.0     Black
1        77.0         Mitigated  No Restraints      F  34.0  Hispanic
2        77.0         Mitigated  No Restraints      M  34.0     Black
3        83.0         Mitigated  No Restraints      F  15.0  Hispanic
4        71.0         Mitigated  No Restraints      M  16.0  Hispanic
...       ...               ...            ...    ...   ...       ...
1048559   NaN               NaN            NaN    NaN   NaN       NaN
1048560   NaN               NaN            NaN    NaN   NaN       NaN
1048561   NaN               NaN            NaN    NaN   NaN       NaN
1048562   NaN               NaN            NaN    NaN   NaN       NaN
1048563   NaN               NaN            NaN    NaN   NaN       NaN

[1048564 rows x 6 columns]

In [12]:
df_q4 = df_q4.dropna(subset=["Pct"])

In [13]:
df_q4

      Pct Intervention Type     Restraints Gender   Age      Race
0    81.0   Juvenile Report  No Restraints      M  14.0     Black
1    77.0         Mitigated  No Restraints      F  34.0  Hispanic
2    77.0         Mitigated  No Restraints      M  34.0     Black
3    83.0         Mitigated  No Restraints      F  15.0  Hispanic
4    71.0         Mitigated  No Restraints      M  16.0  Hispanic
..    ...               ...            ...    ...   ...       ...
104  14.0   Child in Crisis  No Restraints      F  17.0  Hispanic
105  72.0         Mitigated  No Restraints      M   6.0  Hispanic
106  61.0         Mitigated  No Restraints      M   9.0     White
107  72.0   Child in Crisis  No Restraints      M  10.0  Hispanic
108  44.0   Child in Crisis  No Restraints      M  16.0  Hispanic

[109 rows x 6 columns]

In [14]:
df_first_half = pd.concat([df_q1, df_q2])

In [15]:
df_first_half

    Pct Intervention Type     Restraints Gender   Age                Race
0   1.0          Arrested          Metal      M  17.0      White Hispanic
1   1.0   Child in Crisis  No Restraints      F  17.0  Asian/Pacific Isl.
2   1.0   Child in Crisis  No Restraints      F  16.0  Asian/Pacific Isl.
3   1.0   Child in Crisis  No Restraints      M  17.0              Arabic
4   1.0   Child in Crisis          Metal      M  17.0  Asian/Pacific Isl.
..  ...               ...            ...    ...   ...                 ...
32  NaN               NaN            NaN    NaN   NaN                 NaN
33  NaN               NaN            NaN    NaN   NaN                 NaN
34  NaN               NaN            NaN    NaN   NaN                 NaN
35  NaN               NaN            NaN    NaN   NaN                 NaN
36  NaN               NaN            NaN    NaN   NaN                 NaN

[3328 rows x 6 columns]

In [16]:
df_second_half = pd.concat([df_q3, df_q4])

In [17]:
df_second_half

      Pct Intervention Type     Restraints Gender   Age            Race
0    81.0         Mitigated  No Restraints      F  13.0           Black
1    81.0         Mitigated         Velcro      M   9.0           Black
2    62.0         Mitigated  No Restraints      M  30.0           Black
3     9.0         Mitigated  No Restraints      M  14.0  Black Hispanic
4     9.0         Mitigated  No Restraints      M  14.0  White Hispanic
..    ...               ...            ...    ...   ...             ...
104  14.0   Child in Crisis  No Restraints      F  17.0        Hispanic
105  72.0         Mitigated  No Restraints      M   6.0        Hispanic
106  61.0         Mitigated  No Restraints      M   9.0           White
107  72.0   Child in Crisis  No Restraints      M  10.0        Hispanic
108  44.0   Child in Crisis  No Restraints      M  16.0        Hispanic

[134 rows x 6 columns]

In [18]:
SSA_2020_PCT_df = pd.concat([df_first_half, df_second_half])

In [19]:
SSA_2020_PCT_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3462 entries, 0 to 108
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Pct                3448 non-null   float64
 1   Intervention Type  3448 non-null   object
 2   Restraints         3448 non-null   object
 3   Gender             3448 non-null   object
 4   Age                3362 non-null   float64
 5   Race               3448 non-null   object
dtypes: float64(2), object(4)
memory usage: 189.3+ KB

In [20]:
SSA_2020_PCT_df.to_csv('data/clean_SSA_2020_PCT.csv', encoding='utf-8')