In [1]:
!pip install -r requirements.txt

Requirement already satisfied: numpy in /opt/conda/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.20.2)
Requirement already satisfied: pandas in /opt/conda/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (1.2.4)
Collecting sklearn
  Using cached sklearn-0.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.8/site-packages (from pandas->-r requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.8/site-packages (from pandas->-r requirements.txt (line 2)) (2021.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas->-r requirements.txt (line 2)) (1.15.0)
Collecting scikit-learn
  Using cached scikit_learn-0.24.2-cp38-cp38-manylinux2010_x86_64.whl (24.9 MB)
Collecting joblib>=0.11
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.8/site-packages (from scikit-learn->sklearn->-r requirements.txt (line 3)) (2.1.0)
Requirement already satisfied: scipy>=0.19.1 in /opt/conda/lib/python3.8/site-packages (from scikit-learn->sklearn->-r requirements.txt (line 3)) (1.6.3)
Installing collected packages: joblib, scikit-learn, sklearn
Successfully installed joblib-1.0.1 scikit-learn-0.24.2 sklearn-0.0

In [2]:
import sklearn
import numpy as np
import pandas as pd

In [3]:
df_q1= pd.read_csv('data/ssa-report-pct-1q-2019.csv')
df_q2 = pd.read_csv('data/ssa-report-pct-2q-2019.csv')
df_q3 = pd.read_csv('data/ssa-report-pct-3q-2019.csv')
df_q4 = pd.read_csv('data/ssa-report-pct-4q-2019.csv')

In [4]:
df_q1

      Pct Intervention Type     Restraints Gender   Age                Race
0       1   Child in Crisis  No Restraints      M  17.0  Asian/Pacific Isl.
1       1   Child in Crisis  No Restraints      M  15.0      White Hispanic
2       1   Child in Crisis  No Restraints      F  15.0         East Indian
3       1   Juvenile Report  No Restraints      M  15.0      White Hispanic
4       1         Mitigated  No Restraints      M  17.0               Black
...   ...               ...            ...    ...   ...                 ...
3582  123         Mitigated  No Restraints      F  16.0               White
3583  123         Mitigated  No Restraints      M  16.0      Black Hispanic
3584  123   Child in Crisis  No Restraints      M  15.0      White Hispanic
3585  123         Mitigated  No Restraints      F  15.0               White
3586  123   Child in Crisis  No Restraints      F  17.0               Black

[3587 rows x 6 columns]

In [5]:
df_q2

      Pct     Intervention     Restraints Gender   Age            Race
0      43        Mitigated  No Restraints      M  16.0  White Hispanic
1      43  Juvenile Report          Metal      M  16.0  White Hispanic
2     100  Juvenile Report          Metal      M  15.0           Black
3     111          Summons  No Restraints      M  19.0  White Hispanic
4      47         Arrested          Metal      M  15.0  White Hispanic
...   ...              ...            ...    ...   ...             ...
3239   47  Juvenile Report  No Restraints      F  15.0           Black
3240    7  Child in Crisis  No Restraints      F   7.0  White Hispanic
3241   47  Juvenile Report  No Restraints      F  14.0  White Hispanic
3242   75         Arrested          Metal      M  26.0           Black
3243   20         Arrested          Metal      F  17.0           Black

[3244 rows x 6 columns]

In [6]:
df_q2 = df_q2.rename(columns = {"Intervention":"Intervention Type"})

In [7]:
df_q3

      Pct Intervention Type     Restraints Gender   Age                Race
0       1         Mitigated  No Restraints      F  18.0               Black
1       1         Mitigated  No Restraints      M  15.0               Black
2       1   Child in Crisis  No Restraints      F  13.0  Asian/Pacific Isl.
3       5   Juvenile Report  No Restraints      M  16.0      White Hispanic
4       5         Mitigated  No Restraints      M  15.0      White Hispanic
...   ...               ...            ...    ...   ...                 ...
1143  123         Mitigated  No Restraints      M  17.0      White Hispanic
1144  123         Mitigated  No Restraints      M  15.0      White Hispanic
1145  123         Mitigated  No Restraints      M  15.0               Black
1146  123   Juvenile Report  No Restraints      M  13.0               White
1147  123         Mitigated  No Restraints      M  16.0              Arabic

[1148 rows x 6 columns]

In [8]:
df_q4

      Pct Intervention Type     Restraints Gender   Age                Race
0       1          Arrested          Metal      F  15.0               Black
1       1   Child in Crisis  No Restraints      M  16.0              Arabic
2       1   Child in Crisis  No Restraints      M  15.0               Black
3       1   Child in Crisis  No Restraints      M  13.0  Asian/Pacific Isl.
4       1   Child in Crisis          Metal      M  15.0               Black
...   ...               ...            ...    ...   ...                 ...
3455  123         Mitigated  No Restraints      M  17.0               Black
3456  123         Mitigated  No Restraints      M  12.0               White
3457  123         Mitigated  No Restraints      M  16.0               White
3458  123         Mitigated  No Restraints      M  13.0      White Hispanic
3459  123           Summons          Metal      M  18.0               Black

[3460 rows x 6 columns]

In [9]:
df_first_half = df_first_half.rename(columns = {"Intervention":"Intervention Type"})

NameError: name 'df_first_half' is not defined

In [ ]:
df_first_half = pd.concat([df_q1, df_q2])

In [ ]:
df_first_half.info()

In [ ]:
df_second_half = pd.concat([df_q3, df_q4])

In [ ]:
df_second_half

In [ ]:
SSA_2019_PCT_df = pd.concat([df_first_half, df_second_half])

In [ ]:
SSA_2019_PCT_df

In [ ]:
SSA_2019_PCT_df.to_csv('data/clean_SSA_2019_PCT.csv', encoding='utf-8')