In [1]:
!pip install -r requirements.txt

Requirement already satisfied: numpy in /opt/conda/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.20.2)
Requirement already satisfied: pandas in /opt/conda/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (1.2.4)
Requirement already satisfied: sklearn in /opt/conda/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (0.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.8/site-packages (from pandas->-r requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.8/site-packages (from pandas->-r requirements.txt (line 2)) (2021.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas->-r requirements.txt (line 2)) (1.15.0)
Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.8/site-packages (from sklearn->-r requirements.txt (line 3)) (0.24.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.8/site-packages (from scikit-learn->sklearn->-r requirements.txt (line 3)) (2.1.0)
Requirement already satisfied: scipy>=0.19.1 in /opt/conda/lib/python3.8/site-packages (from scikit-learn->sklearn->-r requirements.txt (line 3)) (1.6.3)
Requirement already satisfied: joblib>=0.11 in /opt/conda/lib/python3.8/site-packages (from scikit-learn->sklearn->-r requirements.txt (line 3)) (1.0.1)

In [2]:
import sklearn
import numpy as np
import pandas as pd

In [3]:
df_q1= pd.read_csv('data/ssa-report-school-1q-2018.csv')
df_q2 = pd.read_csv('data/ssa-report-school-2q-2018.csv')
df_q3 = pd.read_csv('data/ssa-report-school-3q-2018.csv')
df_q4 = pd.read_csv('data/ssa-report-school-4q-2018.csv')

In [4]:
df_q1

,School Campus,Intervention Type,Incident Location,Greater Than 21,Scanning Type,Scanning Incident,School Related,School Hours,Enforcment By,Restraints,Force,Type Of Force,Top Charge,SummonsCharge,Classification
0,47 THE AMERICAN SIGN LANGUAGE & ENGLISH SECOND...,Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,N,None,NaN,NaN,NaN
1,47 THE AMERICAN SIGN LANGUAGE & ENGLISH SECOND...,Juvenile Report,On-Site,No,Non-Scanning,N,Y,Y,PATROL,No Restraints,N,None,NaN,NaN,V
2,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
4,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,Y,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3458,YALA MANHATTAN LEARNING CENTER(Manhattan),Summons,On-Site,No,Unannounced,Y,N,Y,PATROL,No Restraints,N,None,NaN,"MARIJUANA, POSSESSION OF",V
3459,Young Women Leadership School Astoria(Queens),Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,N,None,NaN,NaN,NaN
3460,YOUNG WOMEN LEADERSHIP SCHOOL QUEENS CAMPUS(Qu...,Mitigated,On-Site,No,Non-Scanning,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3461,YOUNG WOMEN LEADERSHIP SCHOOL QUEENS CAMPUS(Qu...,Arrested,On-Site,No,Non-Scanning,N,Y,Y,PATROL,Metal,N,None,ASSAULT,NaN,F
3462,YOUNG WOMEN LEADERSHIP SCHOOL QUEENS CAMPUS(Qu...,Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,N,None,NaN,NaN,NaN

In [5]:
df_q1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3463 entries, 0 to 3462
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   School Campus      3463 non-null   object
 1   Intervention Type  3463 non-null   object
 2   Incident Location  3463 non-null   object
 3   Greater Than 21    3463 non-null   object
 4   Scanning Type      3463 non-null   object
 5   Scanning Incident  3463 non-null   object
 6   School Related     3463 non-null   object
 7   School Hours       3463 non-null   object
 8   Enforcment By      2476 non-null   object
 9   Restraints         3463 non-null   object
 10  Force              3463 non-null   object
 11  Type Of Force      3463 non-null   object
 12  Top Charge         320 non-null    object
 13  SummonsCharge      286 non-null    object
 14  Classification     924 non-null    object
dtypes: object(15)
memory usage: 405.9+ KB

In [6]:
df_q2

,School Campus,Intervention Type,Incident Location,Greater Than 21,Scanning Type,Scanning Incident,School Related,School Hours,Enforcment By,Restraints,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,47 THE AMERICAN SIGN LANGUAGE & ENGLISH SECOND...,Juvenile Report,On-Site,No,Non-Scanning,N,Y,Y,SSA,No Restraints,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,47 THE AMERICAN SIGN LANGUAGE & ENGLISH SECOND...,Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,Y,Y,Y,SSA,No Restraints,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,N,Y,Y,DOE,No Restraints,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,N,Y,Y,DOE,No Restraints,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3117,Womens Academy of Excellence(Bronx),Mitigated,On-Site,No,Non-Scanning,N,Y,Y,DOE,No Restraints,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3118,Womens Academy of Excellence(Bronx),Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3119,Yorkville East Middle School(MN),Juvenile Report,On-Site,No,Non-Scanning,N,Y,Y,PATROL,No Restraints,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3120,YOUNG WOMEN LEADERSHIP SCHOOL QUEENS CAMPUS(Qu...,Mitigated,On-Site,No,Unannounced,Y,Y,Y,DOE,No Restraints,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3121,YOUNG WOMEN LEADERSHIP SCHOOL QUEENS CAMPUS(Qu...,Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_q2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3122 entries, 0 to 3121
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   School Campus      3122 non-null   object
 1   Intervention Type  3122 non-null   object
 2   Incident Location  3122 non-null   object
 3   Greater Than 21    3122 non-null   object
 4   Scanning Type      3122 non-null   object
 5   Scanning Incident  3122 non-null   object
 6   School Related     3122 non-null   object
 7   School Hours       3122 non-null   object
 8   Enforcment By      2128 non-null   object
 9   Restraints         3122 non-null   object
 10  Force              3122 non-null   object
 11  Type Of Force      3122 non-null   object
 12  Top Charge         336 non-null    object
 13  SummonsCharge      216 non-null    object
 14  Classification     843 non-null    object
 15  Unnamed: 15        0 non-null      float64
 16  Unnamed: 16        0 non-null      float64
 17  Unnamed: 17        0 non-null      float64
 18  Unnamed: 18        0 non-null      float64
 19  Unnamed: 19        0 non-null      float64
 20  Unnamed: 20        0 non-null      float64
 21  Unnamed: 21        0 non-null      float64
 22  Unnamed: 22        0 non-null      float64
 23  Unnamed: 23        0 non-null      float64
 24  Unnamed: 24        0 non-null      float64
 25  Unnamed: 25        0 non-null      float64
 26  Unnamed: 26        0 non-null      float64
 27  Unnamed: 27        0 non-null      float64
 28  Unnamed: 28        0 non-null      float64
 29  Unnamed: 29        0 non-null      float64
 30  Unnamed: 30        0 non-null      float64
 31  Unnamed: 31        0 non-null      float64
 32  Unnamed: 32        0 non-null      float64
 33  Unnamed: 33        0 non-null      float64
 34  Unnamed: 34        0 non-null      float64
dtypes: float64(20), object(15)
memory usage: 853.8+ KB

In [14]:
# del df_q2["Unnamed: 16"]
# del df_q2["Unnamed: 17"]
del df_q2["Unnamed: 15"]
del df_q2["Unnamed: 18"]
del df_q2["Unnamed: 19"]
del df_q2["Unnamed: 20"]
del df_q2["Unnamed: 21"]
del df_q2["Unnamed: 22"]
del df_q2["Unnamed: 23"]
del df_q2["Unnamed: 24"]
del df_q2["Unnamed: 25"]
del df_q2["Unnamed: 26"]
del df_q2["Unnamed: 27"]
del df_q2["Unnamed: 28"]
del df_q2["Unnamed: 29"]
del df_q2["Unnamed: 30"]
del df_q2["Unnamed: 31"]
del df_q2["Unnamed: 32"]
del df_q2["Unnamed: 33"]
del df_q2["Unnamed: 34"]

In [16]:
df_q2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3122 entries, 0 to 3121
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   School Campus      3122 non-null   object
 1   Intervention Type  3122 non-null   object
 2   Incident Location  3122 non-null   object
 3   Greater Than 21    3122 non-null   object
 4   Scanning Type      3122 non-null   object
 5   Scanning Incident  3122 non-null   object
 6   School Related     3122 non-null   object
 7   School Hours       3122 non-null   object
 8   Enforcment By      2128 non-null   object
 9   Restraints         3122 non-null   object
 10  Force              3122 non-null   object
 11  Type Of Force      3122 non-null   object
 12  Top Charge         336 non-null    object
 13  SummonsCharge      216 non-null    object
 14  Classification     843 non-null    object
dtypes: object(15)
memory usage: 366.0+ KB

In [28]:
df_q3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   School Campus       960 non-null    object
 1   Intervention Type   960 non-null    object
 2   Incident Location   960 non-null    object
 3   Greater Than 21     960 non-null    object
 4   Scanning Type       960 non-null    object
 5   Scanning Incident   960 non-null    object
 6   School Related      960 non-null    object
 7   School Hours        960 non-null    object
 8   Enforcment By       747 non-null    object
 9   Restraints          960 non-null    object
 10  Force               960 non-null    object
 11  Type Of Force       960 non-null    object
 12  Top Charge          110 non-null    object
 13  SummonsCharge       80 non-null     object
 14  Classification      297 non-null    object
dtypes: object(15)
memory usage: 112.6+ KB

In [25]:
df_q3 = df_q3.rename(columns = {"Greater than 21":"Greater Than 21"})

In [35]:
df_q3 = df_q3.rename(columns = {"Incident Location ":"Incident Location"})

In [24]:
df_q4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3710 entries, 0 to 3709
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   School Campus      3710 non-null   object
 1   Intervention Type  3710 non-null   object
 2   Incident Location  3710 non-null   object
 3   Greater Than 21    3710 non-null   object
 4   Scanning Type      3710 non-null   object
 5   Scanning Incident  3710 non-null   object
 6   School Related     3710 non-null   object
 7   School Hours       3710 non-null   object
 8   Enforcment By      2584 non-null   object
 9   Restraints         3710 non-null   object
 10  Force              3710 non-null   object
 11  Type Of Force      3710 non-null   object
 12  Top Charge         296 non-null    object
 13  SummonsCharge      124 non-null    object
 14  Classification     815 non-null    object
dtypes: object(15)
memory usage: 434.9+ KB

In [34]:
df_q4 = df_q4.rename(columns = {"Incident Location ":"Incident Location"})

In [19]:
df_first_half = pd.concat([df_q1, df_q2])

In [40]:
df_first_half

,School Campus,Intervention Type,Incident Location,Greater Than 21,Scanning Type,Scanning Incident,School Related,School Hours,Enforcment By,Restraints,Force,Type Of Force,Top Charge,SummonsCharge,Classification
0,47 THE AMERICAN SIGN LANGUAGE & ENGLISH SECOND...,Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,N,None,NaN,NaN,NaN
1,47 THE AMERICAN SIGN LANGUAGE & ENGLISH SECOND...,Juvenile Report,On-Site,No,Non-Scanning,N,Y,Y,PATROL,No Restraints,N,None,NaN,NaN,V
2,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
4,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,Y,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3117,Womens Academy of Excellence(Bronx),Mitigated,On-Site,No,Non-Scanning,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3118,Womens Academy of Excellence(Bronx),Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,N,None,NaN,NaN,NaN
3119,Yorkville East Middle School(MN),Juvenile Report,On-Site,No,Non-Scanning,N,Y,Y,PATROL,No Restraints,N,None,NaN,NaN,M
3120,YOUNG WOMEN LEADERSHIP SCHOOL QUEENS CAMPUS(Qu...,Mitigated,On-Site,No,Unannounced,Y,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3121,YOUNG WOMEN LEADERSHIP SCHOOL QUEENS CAMPUS(Qu...,Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,N,None,NaN,NaN,NaN

In [39]:
df_first_half.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6585 entries, 0 to 3121
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   School Campus      6585 non-null   object
 1   Intervention Type  6585 non-null   object
 2   Incident Location  6585 non-null   object
 3   Greater Than 21    6585 non-null   object
 4   Scanning Type      6585 non-null   object
 5   Scanning Incident  6585 non-null   object
 6   School Related     6585 non-null   object
 7   School Hours       6585 non-null   object
 8   Enforcment By      4604 non-null   object
 9   Restraints         6585 non-null   object
 10  Force              6585 non-null   object
 11  Type Of Force      6585 non-null   object
 12  Top Charge         656 non-null    object
 13  SummonsCharge      502 non-null    object
 14  Classification     1767 non-null   object
dtypes: object(15)
memory usage: 823.1+ KB

In [36]:
df_second_half = pd.concat([df_q3, df_q4])

In [37]:
df_second_half

,School Campus,Intervention Type,Incident Location,Greater Than 21,Scanning Type,Scanning Incident,School Related,School Hours,Enforcment By,Restraints,Force,Type Of Force,Top Charge,SummonsCharge,Classification
0,Abraham Lincoln HS(BS),Arrested,Off-Site,No,Full-Time,N,N,N,PATROL,Metal,N,None,ROBBERY,NaN,F
1,Abraham Lincoln HS(BS),Arrested,Off-Site,No,Full-Time,N,N,Y,PATROL,Metal,N,None,ROBBERY,NaN,F
2,Abraham Lincoln HS(BS),Arrested,Off-Site,No,Full-Time,N,N,Y,PATROL,Metal,N,None,ROBBERY,NaN,F
3,Abraham Lincoln HS(BS),Juvenile Report,Off-Site,No,Full-Time,N,N,N,PATROL,Metal,N,None,NaN,NaN,M
4,Abraham Lincoln HS(BS),Summons,On-Site,No,Full-Time,Y,Y,Y,UTF,No Restraints,N,None,NaN,POSS. OF KNIFE,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3705,WINGS ACADEMY(Bronx),Mitigated,On-Site,No,Non-Scanning,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3706,WINGS ACADEMY(Bronx),Mitigated,On-Site,No,Non-Scanning,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3707,WINGS ACADEMY(Bronx),Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,N,None,NaN,NaN,NaN
3708,Young Women's Leadership School of the Bronx(XW),Mitigated,On-Site,No,Non-Scanning,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3709,Young Women's Leadership School of the Bronx(XW),Juvenile Report,On-Site,No,Non-Scanning,N,Y,Y,SSA,No Restraints,N,None,NaN,NaN,V

In [38]:
df_second_half.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4670 entries, 0 to 3709
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   School Campus      4670 non-null   object
 1   Intervention Type  4670 non-null   object
 2   Incident Location  4670 non-null   object
 3   Greater Than 21    4670 non-null   object
 4   Scanning Type      4670 non-null   object
 5   Scanning Incident  4670 non-null   object
 6   School Related     4670 non-null   object
 7   School Hours       4670 non-null   object
 8   Enforcment By      3331 non-null   object
 9   Restraints         4670 non-null   object
 10  Force              4670 non-null   object
 11  Type Of Force      4670 non-null   object
 12  Top Charge         406 non-null    object
 13  SummonsCharge      204 non-null    object
 14  Classification     1112 non-null   object
dtypes: object(15)
memory usage: 583.8+ KB

In [41]:
SSA_2018_df = pd.concat([df_first_half, df_second_half])

In [42]:
SSA_2018_df

,School Campus,Intervention Type,Incident Location,Greater Than 21,Scanning Type,Scanning Incident,School Related,School Hours,Enforcment By,Restraints,Force,Type Of Force,Top Charge,SummonsCharge,Classification
0,47 THE AMERICAN SIGN LANGUAGE & ENGLISH SECOND...,Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,N,None,NaN,NaN,NaN
1,47 THE AMERICAN SIGN LANGUAGE & ENGLISH SECOND...,Juvenile Report,On-Site,No,Non-Scanning,N,Y,Y,PATROL,No Restraints,N,None,NaN,NaN,V
2,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
4,Abraham Lincoln HS(BS),Mitigated,On-Site,No,Full-Time,Y,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3705,WINGS ACADEMY(Bronx),Mitigated,On-Site,No,Non-Scanning,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3706,WINGS ACADEMY(Bronx),Mitigated,On-Site,No,Non-Scanning,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3707,WINGS ACADEMY(Bronx),Child in Crisis,On-Site,No,Non-Scanning,N,Y,Y,NaN,No Restraints,N,None,NaN,NaN,NaN
3708,Young Women's Leadership School of the Bronx(XW),Mitigated,On-Site,No,Non-Scanning,N,Y,Y,DOE,No Restraints,N,None,NaN,NaN,NaN
3709,Young Women's Leadership School of the Bronx(XW),Juvenile Report,On-Site,No,Non-Scanning,N,Y,Y,SSA,No Restraints,N,None,NaN,NaN,V

In [44]:
SSA_2018_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11255 entries, 0 to 3709
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   School Campus      11255 non-null  object
 1   Intervention Type  11255 non-null  object
 2   Incident Location  11255 non-null  object
 3   Greater Than 21    11255 non-null  object
 4   Scanning Type      11255 non-null  object
 5   Scanning Incident  11255 non-null  object
 6   School Related     11255 non-null  object
 7   School Hours       11255 non-null  object
 8   Enforcment By      7935 non-null   object
 9   Restraints         11255 non-null  object
 10  Force              11255 non-null  object
 11  Type Of Force      11255 non-null  object
 12  Top Charge         1062 non-null   object
 13  SummonsCharge      706 non-null    object
 14  Classification     2879 non-null   object
dtypes: object(15)
memory usage: 1.4+ MB

In [43]:
SSA_2018_df.to_csv('data/clean_SSA_Report_School_2018.csv', encoding='utf-8')